Models/Hobby.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Csharp_belt.Extensions;

namespace Csharp_belt.Models
{
    public class Hobby
    {
        [Key]
        public int HobbyId { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Description { get; set; }

        public User Creator { get; set; }

        public List<UserHobby> Hobbyists { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.Now;
        public DateTime UpdatedAt { get; set; } = DateTime.Now;
    }
}

Controllers/ActionController.cs
using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Csharp_belt.Models;

namespace Csharp_belt.Controllers
{
    public class ActionController : Controller
    {
        private MyContext _context;
        public ActionController(MyContext context)
        {
            _context = context;
        }

        // CRUD OPS

        [HttpPost("Hobby/Edit/{HobbyId}")] // EDIT/UPDATE
        public IActionResult UpdateHobby(Hobby fromForm, int HobbyId)
        {
            // Hobby toUpdate = _context.Hobbies.FirstOrDefault(w => w.HobbyId == HobbyId);
            if (ModelState.IsValid)
            {
                fromForm.HobbyId = HobbyId;
                _context.Update(fromForm);
                _context.Entry(fromForm).Property("CreatedAt").IsModified = false;
                _context.SaveChanges();
                return RedirectToAction("Dashboard", "Home");
            }
            return View("EditHobby", fromForm);
        }

        [HttpGet("join/{HobbyId}")] //ADD/REMOVE RELATIONSHIP
        public RedirectToActionResult Join(int HobbyId)
        {
            int UserId = (int)HttpContext.Session.GetInt32("UserId");
            UserHobby HobbyList = _context.UserHobbies.Include(b => b.Hobbyist).FirstOrDefault(a => a.Hobbyist.UserId == UserId && a.Hobby.HobbyId == HobbyId);
            if (HobbyList == null)
            {
                UserHobby NewHobby = new UserHobby { };
                User ExistingUser = _context.Users.FirstOrDefault(u => u.UserId == UserId);
                Hobby ExistingHobby = _context.Hobbies.FirstOrDefault(w => w.HobbyId == HobbyId);
                NewHobby.Hobbyist = ExistingUser;
                NewHobby.Hobby = ExistingHobby;
                _context.Add(NewHobby);
                _context.SaveChanges();
            }
            return RedirectToAction("Dashboard", "Home");
        }

        [HttpPost("Hobby/New")] //CREATE NEW/SAVE TO DB
        public IActionResult CreateHobby(Hobby fromForm)
        {
            Hobby Hobby = new Hobby {};
            if (ModelState.IsValid)
            {
                List<Hobby> ExistHobby = _context.Hobbies.Where(h => h.Name == fromForm.Name).ToList();
                if (ExistHobby.Count < 1)
                {
                    int UserId = (int)HttpContext.Session.GetInt32("UserId");

                    User ExistingUser = _context.Users.FirstOrDefault(u => u.UserId == UserId);

                    fromForm.Creator = ExistingUser;

                    _context.Add(fromForm);
                    _context.SaveChanges();

                    UserHobby NewHobby = new UserHobby { };

                    Hobby ExistingHobby = _context.Hobbies.FirstOrDefault(w => w.HobbyId == fromForm.HobbyId);

                    NewHobby.Hobbyist = ExistingUser;

                    NewHobby.Hobby = ExistingHobby;
                    _context.Add(NewHobby);
                    _context.SaveChanges();
                    int HobbyId = ExistingHobby.HobbyId;
                    return RedirectToAction("Hobby", "Home", new { HobbyId = HobbyId });
                }
                else
                {
                    ModelState.AddModelError("Name", "Name must be unique");
                    return View("NewHobby", fromForm);
                }
            }
            return View("NewHobby", Hobby);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Csharp_belt.Models;

namespace Csharp_belt.Controllers
{
    public class HomeController : Controller
    {
        private MyContext _context;

        public HomeController(MyContext context)
        {
            _context = context;
        }


        [HttpGet("")]
        public ViewResult Index()
        {
            RegLogWrapper FormWrapper = new RegLogWrapper { };
            return View("Index", FormWrapper);
        }

        [HttpGet("Hobby")] //dashboard route for geting all and displaying particular table values
        public IActionResult Dashboard()
        {
            int? UserId = HttpContext.Session.GetInt32("UserId");
            if (UserId != null)
            {
                ViewBag.User = _context.Users.FirstOrDefault(a => a.UserId == (HttpContext.Session.GetInt32("UserId")));
                List<Hobby> Hobbies = _context.Hobbies.Include(a => a.Hobbyists).ThenInclude(b => b.Hobbyist).Include(a => a.Creator).ToList();
                return View("Home", Hobbies);
            }
            return RedirectToAction("Index");
        }

        [HttpGet("Hobby/New")] //route displaying form
        public IActionResult NewHobby()
        {
            int? UserId = HttpContext.Session.GetInt32("UserId");
            if (UserId != null)
            {
                Hobby Hobby = new Hobby { };
                return View("NewHobby", Hobby);
            }
            return RedirectToAction("Index");
        }

        [HttpGet("Hobby/{HobbyId}")] // display one from table
        public IActionResult Hobby(int HobbyId)
        {
            int? UserId = HttpContext.Session.GetInt32("UserId");
            if (UserId != null)
            {
                ViewBag.UserId = (int)HttpContext.Session.GetInt32("UserId");
                Hobby Hobby = _context.Hobbies.Include(a => a.Hobbyists).ThenInclude(b => b.Hobbyist).Include(a => a.Creator).FirstOrDefault(w => w.HobbyId == HobbyId);
                return View("Hobby", Hobby);
            }
            return RedirectToAction("Index");
        }

        [HttpGet("Hobby/Edit/{HobbyId}")] // edit/update form
        public IActionResult EditHobby(int HobbyId)
        {
            int? UserId = HttpContext.Session.GetInt32("UserId");
            if (UserId != null)
            {
                ViewBag.UserId = (int)HttpContext.Session.GetInt32("UserId");
                Hobby Hobby = _context.Hobbies.FirstOrDefault(w => w.HobbyId == HobbyId);
                return View("EditHobby", Hobby);
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/RegLoginController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Csharp_belt.Models;

namespace Csharp_belt.Controllers
{
    public class RegLoginController : Controller
    {
        private MyContext _context;
        public RegLoginController(MyContext context)
        {
            _context = context;
        }

        [HttpPost("register")]
        public IActionResult RegisterUser(User fromForm)
        {
            RegLogWrapper FormWrapper = new RegLogWrapper { };
            if (ModelState.IsValid)
            {
                if (_context.Users.Any(u => u.Username == fromForm.Username)) //u.____/fromForm.____ is based on input field
                {
                    ModelState.AddModelError("Username", "Username taken");
                    return View("../Home/Index", FormWrapper);
                }
                else
                {
                    PasswordHasher<User> Hasher = new PasswordHasher<User>();
                    fromForm.Password = Hasher.HashPassword(fromForm, fromForm.Password);
                    _context.Add(fromForm);
                    _context.SaveChanges();
                    HttpContext.Session.SetInt32("UserId", fromForm.UserId);
                    return RedirectToAction("Dashboard", "Home");
                }
            }
            return View("../Home/Index", FormWrapper);
        }

        [HttpPost("login")]
        public IActionResult LoginUser(LoginUser fromForm)
        {
            RegLogWrapper FormWrapper = new RegLogWrapper { };
            if (ModelState.IsValid)
            {
                User ExistingUser = _context.Users.FirstOrDefault(u => u.Username == fromForm.LoginUsername);
                if (ExistingUser == null)
                {
                    ModelState.AddModelError("LoginUsername", "Invalid Username");
                    return View("../Home/Index", FormWrapper);
                }
                PasswordHasher<LoginUser> Hasher = new PasswordHasher<LoginUser>();
                PasswordVerificationResult result = Hasher.VerifyHashedPassword(fromForm, ExistingUser.Password, fromForm.LoginPassword);
                if (result == 0)
                {
                    ModelState.AddModelError("LoginEmail", "Password error");
                    return View("../Home/Index", FormWrapper);
                }
                HttpContext.Session.SetInt32("UserId", ExistingUser.UserId);
                return RedirectToAction("Dashboard", "Home");
            }
            return View("../Home/Index", FormWrapper);
        }

        [HttpGet("logout")]
        public RedirectToActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }
    }
}

Views/Home/Hobby.cshtml
@using Csharp_belt.Models
@model Hobby

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="/css/style_otherrel.css">
</head>

<body>
    <div id="container">

        <div class="hobby">
            <h2>@Model.Name</h2>
            <p>Description: </p>
            <blockquote>@Model.Description</blockquote>
            @if (@Model.Creator.UserId == ViewBag.UserId)
                {
                    <a asp-action="EditHobby" asp-controller="Home" asp-route-ActivityId="@Model.HobbyId"><button>Edit Hobby</button></a>
                }

            <p>@Model.Name Enthusiasts:</p>
            <ul>
                @foreach (var hobbyist in @Model.Hobbyists)
                {
                    <li>@hobbyist.Hobbyist.FirstName</li>
                }
            </ul>

                @if (@Model.Hobbyists.Any(a => a.Hobbyist.UserId == ViewBag.UserId))
                    {
                        <p></p>
                    }
                    else
                    {
                        <td><a asp-action="Join" asp-controller="Action" asp-route-ActivityId="@Model.HobbyId"><button>Add to Hobbies</button></a></td>
                    }

        </div>
    </div>
</body>

</html>

Views/Home/Home.cshtml
@using Csharp_belt.Models
@model List<Hobby>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="/css/style_home.css">

</head>

<body>
    <div id="container">

        <header>
            <h1>Hobbies</h1>
        </header>

        <div class="table">

        <table>
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Enthusiasts</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var hobby in @Model)
                {
                    <tr>
                        <td><a asp-action="Hobby" asp-controller="Home" asp-route-HobbyId="@hobby.HobbyId">@hobby.Name</a></td>
                        <td>@hobby.Hobbyists.Count</td>
                    </tr>
                }
            </tbody>
        </table>

        <a asp-action="NewHobby" asp-controller="Home" method="get"><button>Create a Hobby</button></a>

    </div>

    </div>
</body>

</html>

Views/Home/Index.cshtml
@using Csharp_belt.Models
@model RegLogWrapper

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="stylesheet" href="/css/style.css">
</head>

<body>
    <div id="container">

        <header>
            <h1>Hobby Hub!</h1>
        </header>

        <div class="forms">
            <form asp-action="RegisterUser" asp-controller="RegLogin" method="post">
                <fieldset>
                    <legend>Register</legend>
                    <partial name="../RegLogin/UserPartial.cshtml" model="Model.RegisterForm" />
                    <button type="submit">Signup Now</button>
                </fieldset>
            </form>

            <form asp-action="LoginUser" asp-controller="RegLogin" method="post">
                <fieldset>
                    <legend>Login</legend>
                    <partial name="../RegLogin/LoginPartial.cshtml" model="Model.LoginForm" />
                    <button type="submit">Login</button>
                </fieldset>
            </form>
        </div>

    </div>
</body>

</html>